### PR TITLE
Python 3.12 asyncore to asyncio

### PR DESCRIPTION
**Pull request by FosanzDev**
Since asyncore is not available in python 3.12+, an alternative is added using asyncio.

The asyncore alternative will only be imported if available, so both options are available for Python 3.11 (or less) users.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/520)

### CODE REVIEW

**Comment by tomato42** [comment]
`pep8` errors in codeclimate are relevant

**Comment by tomato42** [comment]
> Codeclimate marks (wrongly) similarities in two completely different methods.

yes, it's a bit too sensitive, don't worry about this, won't block merge based on that

that being said, the failures on python 2.7 are relevant too (possibly other versions), please address those too

**Comment by tomato42** [comment]
unfortunately removing the accent only in the last patch will not work for the bisection tests... :( you'll need to fixup the previous patch wit this change

**Comment by FosanzDev** [comment]
Best way to do this?
New branch from my branch, doing a pr and merging in my repo will work with this?
Anyways I have to add try-except block since asyncio is not in python2 :/

**Comment by tomato42** [comment]
feel free to rebase the patches and force push to this branch; that's why we use Reviewable, so that rebased patches are still easy to review

**Comment by FosanzDev** [comment]
Force pushing interactive rebases 3 times is wild, but code and commits are definitely cleaner!

**Review by tomato42 — APPROVED** [review]
I won't call it wild until we go into double digits :)

overall looks good, but we need the CI passing before I'll merge it

> Reviewed 3 of 3 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/520#-:-O-kF3xn5Ct5bPGnx5tL:b-77ngro)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @FosanzDev)

**Comment by tomato42** [comment]
Sorry, still see issues with the asyncio import on python 2.7...

**Comment by FosanzDev** [comment]
My bad. Completely forgot to force-push the actual changes.

**Comment by tomato42** [comment]
looks like one more test case needs changes

**Comment by FosanzDev** [comment]
Yeah. Now the errors are in the actual unit test I made for my module. Since it is not available in Python 2, how should I solve this? May I remove the unit test?.

**Comment by tomato42** [comment]
skip it for the old python versions, there are examples of doing that in other places; just make a comment to make it clear why it's disabled on older pythons

**Comment by FosanzDev** [comment]
Thanks for the help. I'm not used to unittest.

**Comment by FosanzDev** [comment]
Ran tests with Python 2 and 3. Now it should work fine. Sorry for the inconvenience!
I did it with trial and error really hehe.

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r14, 1 of 4 files at r18, 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/520)* status: all files reviewed, 1 unresolved discussion (waiting on @FosanzDev)

___
*[`unit_tests/test_tlslite_integration_tlsasynciodispatchermixin.py` line 14 at r19](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/520#-O08Wlok6bHib8xzBaoa:-O08Wlok6bHib8xzBaob:bt52ksz) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/af1f53bf1b9d642aa9e8130bb72f0b67b80cfbbf/unit_tests/test_tlslite_integration_tlsasynciodispatchermixin.py#L14)):*
> ```Python
> 
> import sys
> # No unittest2 features are used in this file
> ```

actually there are: skipIf :) that's why py2.6 test run failed
please use
```
try:
   import unittest2 as unittest
except ImportError:
   import unittest
```

**Review by FosanzDev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/520)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @tomato42)

___
*[`unit_tests/test_tlslite_integration_tlsasynciodispatchermixin.py` line 14 at r19](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/520#-O08Wlok6bHib8xzBaoa:-O08rWnb1JaxrEiUmeoE:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/af1f53bf1b9d642aa9e8130bb72f0b67b80cfbbf/unit_tests/test_tlslite_integration_tlsasynciodispatchermixin.py#L14)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

actually there are: skipIf :) that's why py2.6 test run failed
please use
```
try:
   import unittest2 as unittest
except ImportError:
   import unittest
```
</blockquote></details>

Done.

**Review by tomato42 — APPROVED** [review]
> Reviewed 1 of 4 files at r20, 3 of 3 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/520)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @FosanzDev)

**Comment by tomato42** [comment]
Thanks!

**Pull request merged**
